# grumphp.yml
grumphp:
  tasks:
    phpstan_cicd:
      autoload_file: ~
      configuration: ~
      level: 5
      force_patterns: [ ]
      ignore_patterns: [ ]
      triggered_by: [ 'php' ]
      memory_limit: "-1"
      use_grumphp_paths: true
      metadata:
        blocking: true
        task: phpstan
